In [10]:
import pandas as pd 
s = pd.Series(["Akshat", "john", "Joseph"],
             index=[1,2,3])
print(s)

1    Akshat
2      john
3    Joseph
dtype: object

In [14]:
import pandas as pd
goals = pd.Series(
    [12, 8, 15, 50],
    index=["Messi", "Ronaldo", "Neymar","Mbappe"])
print(goals)

Messi      12
Ronaldo     8
Neymar     15
Mbappe     50
dtype: int64

In [15]:
goals.index.is_unique

True

In [16]:
goals["Messi"]

np.int64(12)

In [27]:
import pandas as pd
df = pd.DataFrame(
    {
    "name": ["Akshat", "Bob", "Johny"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Chennai"]
},
    index=[1,2,3]
)

print(df)

     name  age     city
1  Akshat   25    Delhi
2     Bob   30   Mumbai
3   Johny   35  Chennai

In [29]:
import pandas as pd
data = {
    "name": ["Akshat", "Bob", "Johny"],
    "age": [25, 30, 35],
    "city": ["Delhi", "Mumbai", "Chennai"]
}
df = pd.DataFrame(data, index=[1,2,3])

print(df)

     name  age     city
1  Akshat   25    Delhi
2     Bob   30   Mumbai
3   Johny   35  Chennai

In [35]:
import numpy as np
arr = np.array([[1,2], [3,4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

In [36]:
arr

array([[1, 2],
       [3, 4]])

In [39]:
df = pd.read_csv("data.csv")
print(df)

     Name  Age    city
0  Akshat   45   Delhi
1     Bob   34  Mumbai
2    Johy   43   Delhi

In [42]:
df = pd.read_csv("data2.csv", sep=";", usecols=["name","age"])
print(df)

     name  age
0  akshat   45
1   virat   35
2     ana   45

In [50]:
df = pd.read_csv("data2.csv", sep=";", usecols=["name","age"])
df.to_excel("output.xlsx", index=False)

In [51]:
df1 = pd.read_excel("output.xlsx")

In [52]:
print(df1)

     name  age
0  akshat   45
1   virat   35
2     ana   45

In [63]:
df = pd.read_csv("data2.csv", sep=";", usecols=["name","sex"])
excel_df = pd.read_excel("output.xlsx")
final_df = excel_df.merge(df, on="name", how="left")
final_df.to_excel("output.xlsx", index=False)

In [64]:
df2 = pd.read_excel("output.xlsx")
print(df2)

     name  age     sex
0  akshat   45    male
1   virat   35    male
2     ana   45  female

In [7]:
import pandas as pd
data = {
    "Rollno": [1,2,3,4],
    "Name": ["Amit", "Ravi", "Neha", "Priya"],
    "Marks": [80,90,70,100]
}
df = pd.DataFrame(data)
print(df)

   Rollno   Name  Marks
0       1   Amit     80
1       2   Ravi     90
2       3   Neha     70
3       4  Priya    100

In [12]:

df[["Rollno","Marks"]]

   Rollno  Marks
0       1     80
1       2     90
2       3     70
3       4    100

In [18]:

df["Name"]

0     Amit
1     Ravi
2     Neha
3    Priya
Name: Name, dtype: object

In [22]:
 
df.loc[1,"Marks"]

np.int64(90)

In [6]:
df.iloc[3]

Rollno        4
Name      Priya
Marks       100
Name: 3, dtype: object

In [19]:
# i want to get the list of all the students named ravi
df.loc[df["Name"] == "Ravi"]

   Rollno  Name  Marks
1       2  Ravi     90

In [32]:
#get marks of ravi only
df.loc[df["Name"] == "Ravi","Marks"]

1    90
Name: Marks, dtype: int64

In [62]:
import pandas as pd
data = {
    "Rollno": [1,2,3,4,5],
    "Name": ["Amit", "Ravi", "Neha", "Priya","Rohan"],
    "School": ["StJohn", "StJohn", "Xavier", "Xavier", "StJohn"],
    "Marks": [80,90,70,100,95],
    "email": ["amit@gmail.com","ravi@gmail.com","neha@gmail.com", "priya@gmail.com","rohan@gmail.com"]
}
df = pd.DataFrame(data)
print(df)

   Rollno   Name  School  Marks            email
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
2       3   Neha  Xavier     70   neha@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com

In [33]:
#name starts with letter R
df.loc[df["Name"].str.startswith("R")]

   Rollno   Name  Marks
1       2   Ravi     90
4       5  Rohan     95

In [39]:
# studetns who have scored more then 85
df.loc[df["Marks"]>80]

   Rollno   Name  School  Marks
1       2   Ravi  StJohn     90
3       4  Priya  Xavier    100
4       5  Rohan  StJohn     95

In [43]:
df.loc[(df["School"] == "StJohn") & (df["Marks"] > 85)]

   Rollno   Name  School  Marks
1       2   Ravi  StJohn     90
4       5  Rohan  StJohn     95

In [50]:
df.query("School == 'StJohn' and Marks > 85")

   Rollno   Name  School  Marks
1       2   Ravi  StJohn     90
4       5  Rohan  StJohn     95

In [51]:
df.query("School == 'StJohn' or Marks > 85")

   Rollno   Name  School  Marks
0       1   Amit  StJohn     80
1       2   Ravi  StJohn     90
3       4  Priya  Xavier    100
4       5  Rohan  StJohn     95

In [52]:
df["Name"].str.lower()

0     amit
1     ravi
2     neha
3    priya
4    rohan
Name: Name, dtype: object

In [63]:
print(df)

   Rollno   Name  School  Marks            email
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
2       3   Neha  Xavier     70   neha@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com

In [58]:
df["School"].str.contains("stjohn", case=False)  # checks if stjohn is in the school column and is case insensetive

0     True
1     True
2    False
3    False
4     True
Name: School, dtype: bool

In [64]:
df["email"].str.split("@")

0     [amit, gmail.com]
1     [ravi, gmail.com]
2     [neha, gmail.com]
3    [priya, gmail.com]
4    [rohan, gmail.com]
Name: email, dtype: object