In [2]:
##DATA TRANSFORMATION : Once your data is clean, the next step is to reshape , reformat, and reorder it as  needed for analysis. 

###Pandas gives you plenty of flexible tools to do this 


import pandas as pd
data = {
    "Rollno": [1,2,3,4,5],
    "Name": ["Amit", "Ravi", "Neha", "Priya","Rohan"],
    "School": ["StJohn", "StJohn", "Xavier", "Xavier", "StJohn"],
    "Marks": [80,90,70,100,95],
    "email": ["amit@gmail.com","ravi@gmail.com","neha@gmail.com", "priya@gmail.com","rohan@gmail.com"]
}
df = pd.DataFrame(data)
print(df)

   Rollno   Name  School  Marks            email
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
2       3   Neha  Xavier     70   neha@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com

In [3]:

df.sort_values("Marks")   #ascending order

   Rollno   Name  School  Marks            email
2       3   Neha  Xavier     70   neha@gmail.com
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com

In [4]:

df.sort_values("Marks", ascending=False)

   Rollno   Name  School  Marks            email
3       4  Priya  Xavier    100  priya@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
0       1   Amit  StJohn     80   amit@gmail.com
2       3   Neha  Xavier     70   neha@gmail.com

In [5]:
df.sort_values(["Marks", "Name"])

   Rollno   Name  School  Marks            email
2       3   Neha  Xavier     70   neha@gmail.com
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com

In [9]:
#rename a column
df.rename(columns={"email": "parent-email"}, inplace=True)
# df.rename(columns={oldnameofcolumn:newnameofcolumn}, inplace=True)
# inplace: modify the original object itself dont create a new one

In [8]:
df

   Rollno   Name  School  Marks     parent-email
0       1   Amit  StJohn     80   amit@gmail.com
1       2   Ravi  StJohn     90   ravi@gmail.com
2       3   Neha  Xavier     70   neha@gmail.com
3       4  Priya  Xavier    100  priya@gmail.com
4       5  Rohan  StJohn     95  rohan@gmail.com

In [10]:
#chnage the column order
df = df[["Rollno", "Name", "Marks", "School", "parent-email"]]
df

   Rollno   Name  Marks  School     parent-email
0       1   Amit     80  StJohn   amit@gmail.com
1       2   Ravi     90  StJohn   ravi@gmail.com
2       3   Neha     70  Xavier   neha@gmail.com
3       4  Priya    100  Xavier  priya@gmail.com
4       5  Rohan     95  StJohn  rohan@gmail.com