In [10]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Amit", "Akshat", None],
    "Age": [25,None, 35],
    "Marks": [80,90,None]
}
df = pd.DataFrame(data)
print(df)

     Name   Age  Marks
0    Amit  25.0   80.0
1  Akshat   NaN   90.0
2    None  35.0    NaN

In [11]:
df.isnull()

    Name    Age  Marks
0  False  False  False
1  False   True  False
2   True  False   True

In [12]:
#how many sum of all the Null values are there in each column
df.isnull().sum()

Name     1
Age      1
Marks    1
dtype: int64

In [13]:
# check if column has atlease one missing value 
df.isnull().any()

Name     True
Age      True
Marks    True
dtype: bool

In [14]:
#check if column is completely none (missing)
df.isnull().all()

Name     False
Age      False
Marks    False
dtype: bool

In [15]:
#find the total missing values in whole Data frame
df.isnull().sum().sum()

np.int64(3)

In [16]:
# Drop missing  data ( We will use dropna())
df.dropna()  # it will drop all the rows which has Null entries

   Name   Age  Marks
0  Amit  25.0   80.0

In [17]:
#Fillna : It is used to fill unknown values 
df.fillna(0)

     Name   Age  Marks
0    Amit  25.0   80.0
1  Akshat   0.0   90.0
2       0  35.0    0.0

In [18]:
# If we want to drop a row if specific column has none
df.dropna(subset=["Age"])

   Name   Age  Marks
0  Amit  25.0   80.0
2  None  35.0    NaN