# NLP Machine Learning Pipeline – SMS Spam Detection

This notebook demonstrates a **complete Natural Language Processing (NLP) machine learning pipeline** using a **real-world dataset**.

Dataset used: **SMS Spam Collection Dataset (UCI Machine Learning Repository)**.

Goal: Build a model that classifies SMS messages as **spam or ham (not spam)**.

We will implement the pipeline twice:

1. **Bag of Words + Naive Bayes**
2. **TF-IDF + Naive Bayes**

This allows us to compare traditional vectorization techniques.

---
## NLP Pipeline Covered

1. Load real-world dataset
2. Text preprocessing
3. Train/test split
4. Feature extraction
   - Bag of Words
   - TF‑IDF
5. Model training (Naive Bayes)
6. Evaluation
7. Comparison of results

## Step 1 — Import Libraries

We use common libraries from the Python NLP ecosystem.

- pandas → data handling
- scikit‑learn → ML models & vectorizers
- matplotlib / seaborn → visualization

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB #one of the ML models
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import seaborn as sns
import matplotlib.pyplot as plt

## Step 2 — Load Real Dataset

We use the **SMS Spam Collection Dataset**.

Source:
https://archive.ics.uci.edu/ml/datasets/sms+spam+collection

Each message is labeled as:

- ham → normal message
- spam → unwanted promotional message

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv"

data = pd.read_table(url, header=None, names=['label','message']) #pandas function read_table

data.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

## Step 3 — Dataset Overview

In [3]:
data.info()
data['label'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    5572 non-null   object
 1   message  5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

label
ham     4825
spam     747
Name: count, dtype: int64

We convert labels into numeric values for the ML model.

- ham → 0
- spam → 1

In [4]:
data['label_num'] = data.label.map({'ham':0,'spam':1}) #

data.head()

  label                                            message  label_num
0   ham  Go until jurong point, crazy.. Available only ...          0
1   ham                      Ok lar... Joking wif u oni...          0
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...          1
3   ham  U dun say so early hor... U c already then say...          0
4   ham  Nah I don't think he goes to usf, he lives aro...          0

 ML/DL

 **1. Train the model**

 show it lots of historical data. This data is called as training data.

 ex-
 weight, height -> gender

 **FEATURES** -> based on what are we are doing the prediction (weight, height)

**LABEL/TARGET** -> the thing that we are trying to predict...gender

label -> which are continuous

predict height(TARGET) given weight (FEATURE) of the person -> regression problem

label -> discrete
weight, height -> gender (Male/ female)
Classification problem

 ML/DL learns patterns from the data

 when the learning is complete we say the model has been trained

 **2. Evaluate the model/ Test the model**

 1. Training data (1000)-> subset of data points(200)....(test)...accuracy(% of answers the model has got right)

 2. Split the data -> training data (800) and testing (200)

 splitting -> unseen data...so that we can check the performabce of the model on unseen data(data it has not seen durig the training)

## Step 4 — Train/Test Split

We split the dataset so that the model is evaluated on **unseen messages**.

Training dataset: we are going to train ML model
Test datasets: check the performce of the model (unseen data)

In [6]:
X_train, X_test, y_train, y_test = train_test_split( #randomly splits
    data['message'], #X(features -> message)
    data['label_num'], #Y(labels  -> spam/ham)
    test_size=0.2, #20% of data is test data
)

In [7]:
X_test.shape, X_train.shape

((1115,), (4457,))

In [ ]:
#Asssignment -> before vectorization  and lemmetization step...

# PART 1 — Bag of Words

Bag of Words converts text into a matrix of **word frequencies**.

Steps:

1. Build vocabulary (unique words in training dataset)
2. Count word occurrences
3. Create document‑term matrix

In [15]:
bow_vectorizer = CountVectorizer(stop_words='english')

X_train_bow = bow_vectorizer.fit_transform(X_train) #Features of training data; 4457 SMS for training
X_test_bow = bow_vectorizer.transform(X_test)

# Why are we applying fit_transform method on training data and transform method on test data

X_train_bow.shape # 4457 SMS messages (size of training data); for each SMS we are creatig a numerical vector of size 7460(vocabulary of the model)

(4457, 7460)

In [27]:
X_train_bow[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

Vocabulary of the model: **like love happy sad hate** [fit_transform]

unique set of words in training data

SMS1: [0 1 2 0 0]

SMS2: []

Trained the model on these vectors

Model has been trained

PREDICTION

SMS_new: "extremely sad"

1. can you feed the text as is? NO
2. Vectorize it: like love happy sad hate
3.  [0 0 0 1 0]

## Train Naive Bayes Model

In [28]:
model_bow = MultinomialNB() #initiakizing NB class
model_bow.fit(X_train_bow, y_train) #trains the model (features, labels[0 for ham and 1 for spam])

pred_bow = model_bow.predict(X_test_bow)

print("Accuracy:", accuracy_score(y_test, pred_bow)) #y_test-> actual labels , pred_bow-> predicted labels

Accuracy: 0.9820627802690582

## Evaluation

In [ ]:
print(classification_report(y_test, pred_bow))

# PART 2 — TF‑IDF

TF‑IDF improves Bag of Words by giving **less importance to common words**.

In [29]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [30]:
X_train_tfidf.shape

(4457, 7460)

## Train Naive Bayes Model

### Naive Bayes Model -> classification problem

DURING THE TRAINING

Training data: 1000 emails

Email: Free stuff.

P(spam) = P(spam/ free) * P(spam/ stuff) = 0.8

0.8 > Threshold(0.5) -> Tag it as spam
prob < threshold -> tag it as ham

P(A/B) = P(A) * P(B/A) / P(B)

**P(spam/free) = P(spam) * P(free/spam) / P(free)**

1000 emails  -> 6000 unique words (Vocabulary of the model)

1000 emails -> 600 ham mails and 400 spam mails

out of 600 ham mails, lets say...100 mails have word "free" in it

out of 400 spam mails, lets say ...200 mails have word "free" in it

P(spam) = 400/1000 = 0.4 (40% percent)

P(free) = 300/1000 = 0.3

P(free/spam) = What is the probability that a spam has word free given it is a spam mail. = 200/400 = 0.5

P(spam/free) = 0.4 * 0.5/0.3 = 2/3 = 0.66

You will repeat same exercise for all the words in vocabulary of your model

P(spam/w1), P(spam/w2)..............P(spam/w6000)

Training of the model is....during training it learns these conditional probabilities....

PREDICTION

mail: free goodies, hurry up!

P(spam) = p(spam/free) * p(spam/goodies) * P(spam/hurry) *P(spam/up)

P(spam) > Threshold -> SPAM mail

P(spam) < Threshold -> HAM mail

In [33]:
model_tfidf = MultinomialNB() #if i want to use threshold different from 0.5...i have to do it externally
model_tfidf.fit(X_train_tfidf, y_train)

pred_tfidf = model_tfidf.predict(X_test_tfidf) #threshold of 0.5

print("Accuracy:", accuracy_score(y_test, pred_tfidf))

Accuracy: 0.9668161434977578

In [39]:
#TO CHANGE THE THRESHOLD...do it externally
probs = model_tfidf.predict_proba(X_test_tfidf)

threshold = 0.7
y_pred_70 = (probs[:,1] > threshold).astype(int)

In [38]:
y_pred_70

array([0, 0, 0, ..., 0, 0, 0])

## Evaluation

In [ ]:
print(classification_report(y_test, pred_tfidf))

# Comparison

Typically TF‑IDF performs slightly better because it reduces the impact of frequent words.